(ns silicon_photonics.actor
  "silicon_photonics clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Silicon photonics / 光電融合 photonic integrated circuit.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; PhotonicDie
   {:db/ident :silicon_photonics.PhotonicDie/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :silicon_photonics.PhotonicDie/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.PhotonicDie/platform :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.PhotonicDie/processNode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.PhotonicDie/areaMm2 :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.PhotonicDie/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.PhotonicDie/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; OpticalWaveguide
   {:db/ident :silicon_photonics.OpticalWaveguide/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :silicon_photonics.OpticalWaveguide/dieId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.OpticalWaveguide/material :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.OpticalWaveguide/widthNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.OpticalWaveguide/lossDbCm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.OpticalWaveguide/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.OpticalWaveguide/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Modulator
   {:db/ident :silicon_photonics.Modulator/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :silicon_photonics.Modulator/dieId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Modulator/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Modulator/bandwidthGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Modulator/vpiV :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Modulator/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Modulator/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Photodetector
   {:db/ident :silicon_photonics.Photodetector/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :silicon_photonics.Photodetector/dieId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Photodetector/material :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Photodetector/responsivityAW :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Photodetector/bandwidthGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Photodetector/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.Photodetector/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; LaserSource
   {:db/ident :silicon_photonics.LaserSource/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :silicon_photonics.LaserSource/dieId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.LaserSource/type :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.LaserSource/wavelengthNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.LaserSource/powerMw :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.LaserSource/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.LaserSource/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; WavelengthChannel
   {:db/ident :silicon_photonics.WavelengthChannel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :silicon_photonics.WavelengthChannel/dieId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.WavelengthChannel/lambdaNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.WavelengthChannel/spacingGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.WavelengthChannel/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.WavelengthChannel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :silicon_photonics.WavelengthChannel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"PhotonicDie" "OpticalWaveguide" "Modulator" "Photodetector" "LaserSource" "WavelengthChannel"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "silicon_photonics: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "silicon_photonics: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "silicon_photonics: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── PhotonicDie ────────────────────────────────────────────────────────────────
(defn create-photonic-die
  "Create a PhotonicDie."
  [port data]
  (require-fields data ["name" "platform"])
  (let [id (new-id "siph_pho")
        e {:db/id id
           :silicon_photonics.PhotonicDie/id id
           :silicon_photonics.PhotonicDie/name (get data :name)
           :silicon_photonics.PhotonicDie/platform (get data :platform)
           :silicon_photonics.PhotonicDie/processNode (get data :processNode)
           :silicon_photonics.PhotonicDie/areaMm2 (as-double (get data :areaMm2))
           :silicon_photonics.PhotonicDie/createdAt (now)
           :silicon_photonics.PhotonicDie/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-photonic-dies
  "List PhotonicDie with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-photonic-dies port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :silicon_photonics.PhotonicDie/id))
         rows (apply-filters rows (:filter opts) [:silicon_photonics.PhotonicDie/name :silicon_photonics.PhotonicDie/platform :silicon_photonics.PhotonicDie/processNode :silicon_photonics.PhotonicDie/areaMm2])]
     (paginate rows opts))))

(defn get-photonic-die
  "Retrieve a PhotonicDie by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-photonic-die port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-photonic-die
  "Update a PhotonicDie; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :silicon_photonics.PhotonicDie/name (get data :name)]))
                   (cond-> (contains? data :platform) (conj [:db/add id :silicon_photonics.PhotonicDie/platform (get data :platform)]))
                   (cond-> (contains? data :processNode) (conj [:db/add id :silicon_photonics.PhotonicDie/processNode (get data :processNode)]))
                   (cond-> (contains? data :areaMm2) (conj [:db/add id :silicon_photonics.PhotonicDie/areaMm2 (as-double (get data :areaMm2))]))
                   (conj [:db/add id :silicon_photonics.PhotonicDie/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-photonic-die
  "Delete a PhotonicDie."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── OpticalWaveguide ────────────────────────────────────────────────────────────────
(defn create-optical-waveguide
  "Create a OpticalWaveguide."
  [port data]
  (require-fields data ["material" "widthNm"])
  (let [id (new-id "siph_opt")
        e {:db/id id
           :silicon_photonics.OpticalWaveguide/id id
           :silicon_photonics.OpticalWaveguide/dieId (get data :dieId)
           :silicon_photonics.OpticalWaveguide/material (get data :material)
           :silicon_photonics.OpticalWaveguide/widthNm (as-double (get data :widthNm))
           :silicon_photonics.OpticalWaveguide/lossDbCm (as-double (get data :lossDbCm))
           :silicon_photonics.OpticalWaveguide/createdAt (now)
           :silicon_photonics.OpticalWaveguide/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-optical-waveguides
  "List OpticalWaveguide with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-optical-waveguides port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :silicon_photonics.OpticalWaveguide/id))
         rows (apply-filters rows (:filter opts) [:silicon_photonics.OpticalWaveguide/dieId :silicon_photonics.OpticalWaveguide/material :silicon_photonics.OpticalWaveguide/widthNm :silicon_photonics.OpticalWaveguide/lossDbCm])]
     (paginate rows opts))))

(defn get-optical-waveguide
  "Retrieve a OpticalWaveguide by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-optical-waveguide port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-optical-waveguide
  "Update a OpticalWaveguide; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dieId) (conj [:db/add id :silicon_photonics.OpticalWaveguide/dieId (get data :dieId)]))
                   (cond-> (contains? data :material) (conj [:db/add id :silicon_photonics.OpticalWaveguide/material (get data :material)]))
                   (cond-> (contains? data :widthNm) (conj [:db/add id :silicon_photonics.OpticalWaveguide/widthNm (as-double (get data :widthNm))]))
                   (cond-> (contains? data :lossDbCm) (conj [:db/add id :silicon_photonics.OpticalWaveguide/lossDbCm (as-double (get data :lossDbCm))]))
                   (conj [:db/add id :silicon_photonics.OpticalWaveguide/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-optical-waveguide
  "Delete a OpticalWaveguide."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Modulator ────────────────────────────────────────────────────────────────
(defn create-modulator
  "Create a Modulator."
  [port data]
  (require-fields data ["type" "bandwidthGhz"])
  (let [id (new-id "siph_mod")
        e {:db/id id
           :silicon_photonics.Modulator/id id
           :silicon_photonics.Modulator/dieId (get data :dieId)
           :silicon_photonics.Modulator/type (get data :type)
           :silicon_photonics.Modulator/bandwidthGhz (as-double (get data :bandwidthGhz))
           :silicon_photonics.Modulator/vpiV (as-double (get data :vpiV))
           :silicon_photonics.Modulator/createdAt (now)
           :silicon_photonics.Modulator/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-modulators
  "List Modulator with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-modulators port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :silicon_photonics.Modulator/id))
         rows (apply-filters rows (:filter opts) [:silicon_photonics.Modulator/dieId :silicon_photonics.Modulator/type :silicon_photonics.Modulator/bandwidthGhz :silicon_photonics.Modulator/vpiV])]
     (paginate rows opts))))

(defn get-modulator
  "Retrieve a Modulator by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-modulator port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-modulator
  "Update a Modulator; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dieId) (conj [:db/add id :silicon_photonics.Modulator/dieId (get data :dieId)]))
                   (cond-> (contains? data :type) (conj [:db/add id :silicon_photonics.Modulator/type (get data :type)]))
                   (cond-> (contains? data :bandwidthGhz) (conj [:db/add id :silicon_photonics.Modulator/bandwidthGhz (as-double (get data :bandwidthGhz))]))
                   (cond-> (contains? data :vpiV) (conj [:db/add id :silicon_photonics.Modulator/vpiV (as-double (get data :vpiV))]))
                   (conj [:db/add id :silicon_photonics.Modulator/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-modulator
  "Delete a Modulator."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Photodetector ────────────────────────────────────────────────────────────────
(defn create-photodetector
  "Create a Photodetector."
  [port data]
  (require-fields data ["material" "responsivityAW"])
  (let [id (new-id "siph_pho")
        e {:db/id id
           :silicon_photonics.Photodetector/id id
           :silicon_photonics.Photodetector/dieId (get data :dieId)
           :silicon_photonics.Photodetector/material (get data :material)
           :silicon_photonics.Photodetector/responsivityAW (as-double (get data :responsivityAW))
           :silicon_photonics.Photodetector/bandwidthGhz (as-double (get data :bandwidthGhz))
           :silicon_photonics.Photodetector/createdAt (now)
           :silicon_photonics.Photodetector/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-photodetectors
  "List Photodetector with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-photodetectors port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :silicon_photonics.Photodetector/id))
         rows (apply-filters rows (:filter opts) [:silicon_photonics.Photodetector/dieId :silicon_photonics.Photodetector/material :silicon_photonics.Photodetector/responsivityAW :silicon_photonics.Photodetector/bandwidthGhz])]
     (paginate rows opts))))

(defn get-photodetector
  "Retrieve a Photodetector by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-photodetector port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-photodetector
  "Update a Photodetector; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dieId) (conj [:db/add id :silicon_photonics.Photodetector/dieId (get data :dieId)]))
                   (cond-> (contains? data :material) (conj [:db/add id :silicon_photonics.Photodetector/material (get data :material)]))
                   (cond-> (contains? data :responsivityAW) (conj [:db/add id :silicon_photonics.Photodetector/responsivityAW (as-double (get data :responsivityAW))]))
                   (cond-> (contains? data :bandwidthGhz) (conj [:db/add id :silicon_photonics.Photodetector/bandwidthGhz (as-double (get data :bandwidthGhz))]))
                   (conj [:db/add id :silicon_photonics.Photodetector/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-photodetector
  "Delete a Photodetector."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── LaserSource ────────────────────────────────────────────────────────────────
(defn create-laser-source
  "Create a LaserSource."
  [port data]
  (require-fields data ["type" "wavelengthNm"])
  (let [id (new-id "siph_las")
        e {:db/id id
           :silicon_photonics.LaserSource/id id
           :silicon_photonics.LaserSource/dieId (get data :dieId)
           :silicon_photonics.LaserSource/type (get data :type)
           :silicon_photonics.LaserSource/wavelengthNm (as-double (get data :wavelengthNm))
           :silicon_photonics.LaserSource/powerMw (as-double (get data :powerMw))
           :silicon_photonics.LaserSource/createdAt (now)
           :silicon_photonics.LaserSource/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-laser-sources
  "List LaserSource with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-laser-sources port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :silicon_photonics.LaserSource/id))
         rows (apply-filters rows (:filter opts) [:silicon_photonics.LaserSource/dieId :silicon_photonics.LaserSource/type :silicon_photonics.LaserSource/wavelengthNm :silicon_photonics.LaserSource/powerMw])]
     (paginate rows opts))))

(defn get-laser-source
  "Retrieve a LaserSource by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-laser-source port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-laser-source
  "Update a LaserSource; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dieId) (conj [:db/add id :silicon_photonics.LaserSource/dieId (get data :dieId)]))
                   (cond-> (contains? data :type) (conj [:db/add id :silicon_photonics.LaserSource/type (get data :type)]))
                   (cond-> (contains? data :wavelengthNm) (conj [:db/add id :silicon_photonics.LaserSource/wavelengthNm (as-double (get data :wavelengthNm))]))
                   (cond-> (contains? data :powerMw) (conj [:db/add id :silicon_photonics.LaserSource/powerMw (as-double (get data :powerMw))]))
                   (conj [:db/add id :silicon_photonics.LaserSource/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-laser-source
  "Delete a LaserSource."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── WavelengthChannel ────────────────────────────────────────────────────────────────
(defn create-wavelength-channel
  "Create a WavelengthChannel."
  [port data]
  (require-fields data ["lambdaNm" "spacingGhz"])
  (let [id (new-id "siph_wav")
        e {:db/id id
           :silicon_photonics.WavelengthChannel/id id
           :silicon_photonics.WavelengthChannel/dieId (get data :dieId)
           :silicon_photonics.WavelengthChannel/lambdaNm (as-double (get data :lambdaNm))
           :silicon_photonics.WavelengthChannel/spacingGhz (as-double (get data :spacingGhz))
           :silicon_photonics.WavelengthChannel/dataRateGbps (as-double (get data :dataRateGbps))
           :silicon_photonics.WavelengthChannel/createdAt (now)
           :silicon_photonics.WavelengthChannel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-wavelength-channels
  "List WavelengthChannel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-wavelength-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :silicon_photonics.WavelengthChannel/id))
         rows (apply-filters rows (:filter opts) [:silicon_photonics.WavelengthChannel/dieId :silicon_photonics.WavelengthChannel/lambdaNm :silicon_photonics.WavelengthChannel/spacingGhz :silicon_photonics.WavelengthChannel/dataRateGbps])]
     (paginate rows opts))))

(defn get-wavelength-channel
  "Retrieve a WavelengthChannel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-wavelength-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-wavelength-channel
  "Update a WavelengthChannel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :dieId) (conj [:db/add id :silicon_photonics.WavelengthChannel/dieId (get data :dieId)]))
                   (cond-> (contains? data :lambdaNm) (conj [:db/add id :silicon_photonics.WavelengthChannel/lambdaNm (as-double (get data :lambdaNm))]))
                   (cond-> (contains? data :spacingGhz) (conj [:db/add id :silicon_photonics.WavelengthChannel/spacingGhz (as-double (get data :spacingGhz))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :silicon_photonics.WavelengthChannel/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :silicon_photonics.WavelengthChannel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-wavelength-channel
  "Delete a WavelengthChannel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/photonicdies" :op :create :entity "PhotonicDie"}
   {:method "GET" :path "/v1/photonicdies" :op :list :entity "PhotonicDie"}
   {:method "GET" :path "/v1/photonicdies/:id" :op :get :entity "PhotonicDie"}
   {:method "PATCH" :path "/v1/photonicdies/:id" :op :update :entity "PhotonicDie"}
   {:method "DELETE" :path "/v1/photonicdies/:id" :op :delete :entity "PhotonicDie"}
   {:method "POST" :path "/v1/opticalwaveguides" :op :create :entity "OpticalWaveguide"}
   {:method "GET" :path "/v1/opticalwaveguides" :op :list :entity "OpticalWaveguide"}
   {:method "GET" :path "/v1/opticalwaveguides/:id" :op :get :entity "OpticalWaveguide"}
   {:method "PATCH" :path "/v1/opticalwaveguides/:id" :op :update :entity "OpticalWaveguide"}
   {:method "DELETE" :path "/v1/opticalwaveguides/:id" :op :delete :entity "OpticalWaveguide"}
   {:method "POST" :path "/v1/modulators" :op :create :entity "Modulator"}
   {:method "GET" :path "/v1/modulators" :op :list :entity "Modulator"}
   {:method "GET" :path "/v1/modulators/:id" :op :get :entity "Modulator"}
   {:method "PATCH" :path "/v1/modulators/:id" :op :update :entity "Modulator"}
   {:method "DELETE" :path "/v1/modulators/:id" :op :delete :entity "Modulator"}
   {:method "POST" :path "/v1/photodetectors" :op :create :entity "Photodetector"}
   {:method "GET" :path "/v1/photodetectors" :op :list :entity "Photodetector"}
   {:method "GET" :path "/v1/photodetectors/:id" :op :get :entity "Photodetector"}
   {:method "PATCH" :path "/v1/photodetectors/:id" :op :update :entity "Photodetector"}
   {:method "DELETE" :path "/v1/photodetectors/:id" :op :delete :entity "Photodetector"}
   {:method "POST" :path "/v1/lasersources" :op :create :entity "LaserSource"}
   {:method "GET" :path "/v1/lasersources" :op :list :entity "LaserSource"}
   {:method "GET" :path "/v1/lasersources/:id" :op :get :entity "LaserSource"}
   {:method "PATCH" :path "/v1/lasersources/:id" :op :update :entity "LaserSource"}
   {:method "DELETE" :path "/v1/lasersources/:id" :op :delete :entity "LaserSource"}
   {:method "POST" :path "/v1/wavelengthchannels" :op :create :entity "WavelengthChannel"}
   {:method "GET" :path "/v1/wavelengthchannels" :op :list :entity "WavelengthChannel"}
   {:method "GET" :path "/v1/wavelengthchannels/:id" :op :get :entity "WavelengthChannel"}
   {:method "PATCH" :path "/v1/wavelengthchannels/:id" :op :update :entity "WavelengthChannel"}
   {:method "DELETE" :path "/v1/wavelengthchannels/:id" :op :delete :entity "WavelengthChannel"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"photonicdies" {:create create-photonic-die :list list-photonic-dies :get get-photonic-die :update update-photonic-die :delete delete-photonic-die}
   "opticalwaveguides" {:create create-optical-waveguide :list list-optical-waveguides :get get-optical-waveguide :update update-optical-waveguide :delete delete-optical-waveguide}
   "modulators" {:create create-modulator :list list-modulators :get get-modulator :update update-modulator :delete delete-modulator}
   "photodetectors" {:create create-photodetector :list list-photodetectors :get get-photodetector :update update-photodetector :delete delete-photodetector}
   "lasersources" {:create create-laser-source :list list-laser-sources :get get-laser-source :update update-laser-source :delete delete-laser-source}
   "wavelengthchannels" {:create create-wavelength-channel :list list-wavelength-channels :get get-wavelength-channel :update update-wavelength-channel :delete delete-wavelength-channel}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "silicon_photonics-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
